const OPERATORS = {
	EQUAL: 1,
	LOWER: 2,
	LOWEREQUAL: 3,
	HIGHER: 4,
	HIGHEREQUAL: 5,
	NOTEQUAL: 6,
	CONTAINS: 8
};

export const OPERATOR_NUMBER = {
	EQUAL:       OPERATORS.EQUAL,
	LOWER:       OPERATORS.LOWER,
	LOWEREQUAL:  OPERATORS.LOWEREQUAL,
	HIGHER:      OPERATORS.HIGHER,
	HIGHEREQUAL: OPERATORS.HIGHEREQUAL,
	NOTEQUAL:    OPERATORS.NOTEQUAL
}

export const OPERATOR_TEXT = {
	EQUAL:    OPERATORS.EQUAL,
	NOTEQUAL: OPERATORS.NOTEQUAL,
	CONTAINS: OPERATORS.CONTAINS
}

export default OPERATORS